export const environment = {
    production: false,
    countries: [
        { name: "Argentina", code: "AR", flag: 'https://www.worldometers.info/img/flags/ar-flag.gif' },
        { name: "Austria", code: "AT", flag: 'https://www.worldometers.info/img/flags/au-flag.gif' },
        { name: "Australia", code: "AU", flag: 'https://www.worldometers.info/img/flags/at-flag.gif' },
        { name: "Bélgica", code: "BE", flag: 'https://www.worldometers.info/img/flags/be-flag.gif' },
        { name: "Bolivia", code: "BO", flag: 'https://www.worldometers.info/img/flags/bl-flag.gif' },
        { name: "Brasil", code: "BR", flag: 'https://www.worldometers.info/img/flags/br-flag.gif' },
        { name: "Canadá", code: "CA", flag: 'https://www.worldometers.info/img/flags/ca-flag.gif' },
        { name: "Suiza", code: "CH", flag: 'https://www.worldometers.info/img/flags/sz-flag.gif' },
        { name: "Chile", code: "CL", flag: 'https://www.worldometers.info/img/flags/ci-flag.gif' },
        { name: "Colombia", code: "CO", flag: 'https://www.worldometers.info/img/flags/co-flag.gif' },
        { name: "Costa Rica", code: "CR", flag: 'https://www.worldometers.info/img/flags/cs-flag.gif' },
        { name: "Alemania", code: "DE", flag: 'https://www.worldometers.info/img/flags/gm-flag.gif' },
        { name: "Egipto", code: "EG", flag: 'https://www.worldometers.info/img/flags/eg-flag.gif' },
        { name: "España", code: "ES", flag: 'https://www.worldometers.info/img/flags/sp-flag.gif' },
        { name: "Francia", code: "FR", flag: 'https://www.worldometers.info/img/flags/fr-flag.gif' },
        { name: "Reino Unido", code: "GB", flag: 'https://www.worldometers.info/img/flags/uk-flag.gif' },
        { name: "India", code: "IN", flag: 'https://www.worldometers.info/img/flags/in-flag.gif' },
        { name: "Irak", code: "IQ", flag: 'https://www.worldometers.info/img/flags/iz-flag.gif' },
        { name: "Italia", code: "IT", flag: 'https://www.worldometers.info/img/flags/it-flag.gif' },
        { name: "Jamaica", code: "JM", flag: 'https://www.worldometers.info/img/flags/jm-flag.gif' },
        { name: "Japón", code: "JP", flag: 'https://www.worldometers.info/img/flags/ja-flag.gif' },
        { name: "México", code: "MX", flag: 'https://www.worldometers.info/img/flags/mx-flag.gif' },
        { name: "Países Bajos", code: "NL", flag: 'https://www.worldometers.info/img/flags/nl-flag.gif' },
        { name: "Noruega", code: "NO", flag: 'https://www.worldometers.info/img/flags/no-flag.gif' },
        { name: "Nueva Zelanda", code: "NZ", flag: 'https://www.worldometers.info/img/flags/nz-flag.gif' },
        { name: "Perú", code: "PE", flag: 'https://www.worldometers.info/img/flags/pe-flag.gif' },
        { name: "Puerto Rico", code: "PR", flag: 'https://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_Puerto_Rico.svg' },
        { name: "Arabia Saudita", code: "SA", flag: 'https://www.worldometers.info/img/flags/sa-flag.gif' },
        { name: "Estados Unidos", code: "US", flag: 'https://www.worldometers.info/img/flags/us-flag.gif' },
        { name: "Venezuela", code: "VE", flag: 'https://www.worldometers.info/img/flags/ve-flag.gif' }
    ]
};
